# Author: Cuong Tran
FROM facelog

RUN pip3 install httpx>=0.18.2  
RUN pip3 install requests>=2.25.1
RUN pip3 install unidecode>=1.3.4
RUN pip3 install pyyaml>=5.4.1
RUN pip3 install pycryptodome==3.10.1



# Minimize image size
RUN (apt-get autoremove -y; \
     apt-get autoclean -y)

ENV QT_X11_NO_MITSHM=1

CMD ["bash"]
