# Author: Cuong Tran
FROM quantumlabs/jetson-nano_tf1.15_cv2_4.4.0_py3.6:1.0

RUN apt-get update
RUN apt-get -y install --reinstall libcanberra-gtk-module
RUN apt-get -y install git cmake
RUN apt-get -y install libprotobuf-dev protobuf-compiler
RUN pip3 install onnx
RUN wget https://nvidia.box.com/shared/static/jy7nqva7l88mq9i8bw3g3sklzf4kccn2.whl -O onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl
RUN pip3 install onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl

# Minimize image size
RUN (apt-get autoremove -y; \
     apt-get autoclean -y)

ENV QT_X11_NO_MITSHM=1

CMD ["bash"]
