# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class tab2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.screen = QtWidgets.QLabel(Form)
        self.screen.setGeometry(QtCore.QRect(520, 120, 680, 480))
        self.screen.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.screen.setText("")
        self.screen.setObjectName("screen")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(110, 200, 301, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.position = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.position.setObjectName("position")
        self.gridLayout.addWidget(self.position, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 80, 281, 91))
        self.label_4.setObjectName("label_4")
        self.shot = QtWidgets.QPushButton(Form)
        self.shot.setGeometry(QtCore.QRect(210, 400, 81, 51))
        self.shot.setObjectName("shot")
        self.complete = QtWidgets.QPushButton(Form)
        self.complete.setGeometry(QtCore.QRect(210, 480, 81, 51))
        self.complete.setObjectName("complete")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Position"))
        self.label_2.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic; text-decoration: underline; color:#204a87;\">Add new employee</span></p></body></html>"))
        self.shot.setText(_translate("Form", "Shot"))
        self.complete.setText(_translate("Form", "Complete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
